const constants = {
  CANCEL_FETCHING: "CANCEL_FETCHING",

  SET_CURRENT_SONG: "SET_CURRENT_SONG",

  // PLAYLIST ACTIONS
  ADD_TO_PLAYLIST: "ADD_TO_PLAYLIST",
  REMOVE_FROM_PLAYLIST: "REMOVE_FROM_PLAYLIST",

  // LIKED SONG ACTIONS
  ADD_TO_LIKED_SONGS: "ADD_TO_LIKED_SONGS",
  REMOVE_FROM_LIKED_SONGS: "REMOVE_FROM_LIKED_SONGS",

  // SET USER
  SET_USER: "SET_USER",

  // INITIAL SONG ACTIONS
  SET_INITIAL_SONG: "ADD_TO_INITIAL_SONG",

  // SEARCH RESULT ACTIONS
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
};

export default constants;
